import Head from 'next/head';
import Image from 'next/image';
import styles from '../styles/Home.module.css';
// import MoreVertIcon from '@mui/icons-material/MoreVert';
import ChatHeader from '../components/chatHeader';

export default function Home() {
  return (
    <div data-theme="cupcake">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main><br/>
        <h3 className="text-3xl font-bold text-center">Chat Header UI</h3><br/>
        <div>
        <ChatHeader />
        </div>
      </main>

    </div>
  )
}
